// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJnUl7aoZf6DaBshSp_9x2H5KGlLNxLFg',
    appId: '1:219780326252:web:bfc6701b737cc92a9f0949',
    messagingSenderId: '219780326252',
    projectId: 'piano-project-7a1c7',
    authDomain: 'piano-project-7a1c7.firebaseapp.com',
    storageBucket: 'piano-project-7a1c7.firebasestorage.app',
    measurementId: 'G-08851VFDW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHgt2XnTMVrszo5si6pJAMABw2WlR4cA',
    appId: '1:219780326252:android:8a0e56a22f8321f29f0949',
    messagingSenderId: '219780326252',
    projectId: 'piano-project-7a1c7',
    storageBucket: 'piano-project-7a1c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZc-fpeE-9tCDeOGLcN8359eQqLRjIkcY',
    appId: '1:219780326252:ios:72254fc4344920069f0949',
    messagingSenderId: '219780326252',
    projectId: 'piano-project-7a1c7',
    storageBucket: 'piano-project-7a1c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZc-fpeE-9tCDeOGLcN8359eQqLRjIkcY',
    appId: '1:219780326252:ios:72254fc4344920069f0949',
    messagingSenderId: '219780326252',
    projectId: 'piano-project-7a1c7',
    storageBucket: 'piano-project-7a1c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJnUl7aoZf6DaBshSp_9x2H5KGlLNxLFg',
    appId: '1:219780326252:web:3fe03a2e7d63d9619f0949',
    messagingSenderId: '219780326252',
    projectId: 'piano-project-7a1c7',
    authDomain: 'piano-project-7a1c7.firebaseapp.com',
    storageBucket: 'piano-project-7a1c7.firebasestorage.app',
    measurementId: 'G-C9Y33CWTYZ',
  );
}
